oauth_server_auth_login:
    path: /oauth/v2/auth_login
    controller: OAuthServerBundle:Security:login

oauth_server_auth_login_check:
    path: /oauth/v2/auth_login_check
    controller: OAuthServerBundle:Security:loginCheck

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
